language: ruby
sudo: false
before_install:
  - rvm @global do gem uninstall bundler --all --executables
  - gem uninstall bundler --all --executables
  - gem install bundler -v '<= 1.10.6'
rvm:
  - 2.2.4
  - 2.1.8
  - 2.0.0
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
script:
  - bundle exec rake
  - bundle exec rake build
